HI_MET_TOESTEL          = "http://www.hi.nl/Productinfo/Abonnement/Tarieven-Hi-Abonnement.htm"
HI_SIM_ONLY             = "http://www.hi.nl/Productinfo/Hi-Simonly-abonnement.htm"
T_MOBILE_RELAX          = "http://www.t-mobile.nl/mobiel-abonnement/tarieven"
T_MOBILE_RELAX_ONLINE   = "http://www.t-mobile.nl/mobiel-abonnement/tarieven"
T_MOBILE_RELAX_SIM_ONLY = "http://www.t-mobile.nl/mobiel-abonnement/tarieven"
T_MOBILE_VOORDEELSIM    = "http://www.t-mobile.nl/mobiel-abonnement/tarieven"
T_MOBILE_IPHONE         = "http://www.t-mobile.nl/mobiel-abonnement/tarieven"
VODAFONE_BELLEN         = "http://www.vodafone.nl/mobiel_bellen/abonnementen/abonnementen_met_toestel/bellen/"
VODAFONE_BELLEN_SMS     = "http://www.vodafone.nl/mobiel_bellen/abonnementen/abonnementen_met_toestel/bel_sms/"
VODAFONE_BELLEN_SMS_WEB = "http://www.vodafone.nl/mobiel_bellen/abonnementen/abonnementen_met_toestel/bel_sms_web"
VODAFONE_SCHERP         = "http://www.vodafone.nl/mobiel_bellen/abonnementen/sim_only_abonnement/vodafone_scherp"
VODAFONE_BELLEN_SMS_SO  = "http://www.vodafone.nl/mobiel_bellen/abonnementen/sim_only_abonnement/bel_sms/tarieven"
VODAFONE_BELLEN_SMS_WEB_SO = "http://www.vodafone.nl/mobiel_bellen/abonnementen/sim_only_abonnement/bel_sms_web/tarieven"
KPN                     = "http://www.kpn.com/is-bin/INTERSHOP.enfinity/WFS/KPN-B2C-Site/nl_NL/-/EUR/DDTProductDetail-ShowSubscriptionDL"
KPN_SIM_ONLY            = "http://www.kpn.com/prive/mobiel/tarieven/Abonnementen.htm"
TELFORT_MET_TOESTEL     = "http://shop.telfort.nl/abonnement/informatie/"
TELFORT_UNLIMITED       = "http://shop.telfort.nl/sim-only/informatie/unlimited/"
TELFORT_SIM_ONLY        = "http://shop.telfort.nl/sim-only/informatie/"
BEN                     = "http://www.ben.nl/abonnementen"
                        
GSMARENA                = "http://www.gsmarena.com/"
ESATO                   = "http://www.esato.com/phones/"
                        
INLOG_TMOBILE           = "http://www.t-mobile.nl/my-t-mobile"
INLOG_KPN               = "http://www.kpn.com/inloggen.htm"
INLOG_HI                = "http://www.hi.nl/"
INLOG_VODAFONE          = "https://my.vodafone.nl/prive/my_vodafone?errormessage=&errorcode="
INLOG_TELFORT           = "https://www.telfort.nl/mijntelfort/mobiel/inloggen/"
